[profile.default]
solc = "0.8.19"
src = 'src'
out = 'out'
libs = ['lib']
# Disable the following Solidity feature: https://docs.soliditylang.org/en/v0.8.19/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode
# It interferes with our init code hash in buttonswap-periphery
cbor_metadata = false
bytecodeHash = "none"

[fuzz]
# The number of fuzz runs for fuzz tests
runs = 256

[etherscan]
  arbitrum_one = { key = "${API_KEY_ARBISCAN}" }
  avalanche = { key = "${API_KEY_SNOWTRACE" }
  blast_sepolia = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/168587773/etherscan"}
  bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
  gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}" }
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  polygon = { key = "${API_KEY_POLYGONSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
  arbitrum_one = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
  avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
  blast_sepolia = "https://sepolia.blast.io"
  bnb_smart_chain = "https://bsc-dataseed.binance.org"
  gnosis_chain = "https://rpc.gnosischain.com"
  goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
  localhost = "http://localhost:8545"
  mainnet = "${RPC_URL_MAINNET}"
  optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
  polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
